### ISSUE TITLE
Repeated code

### ISSUE THREAD

**Issue by benureau** [CynthiaRais/Rustichini2015#5]
The `cj_b_cells` and `cj_a_cells` function are identical, save for print statements. Only one of them should exist.

**Comment by CynthiaRais** [comment]
cj_b_cells and cj_a_cells had been merged into a unique function cj_cells as well as functions ov_a_cells and ov_b_cells had been deleted[ here ](https://github.com/CynthiaRais/Rustichini2015/commit/13377410e3629060b484b950d88b6891c1a124b7).
